language: csharp

sudo: required 

before_install:
  - sudo apt-get install unzip curl
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - sudo apt-get install libunwind8 gettext libssl-dev libcurl4-openssl-dev zlib1g libicu-dev uuid-dev
  - dnvm upgrade -r coreclr

script: 
  - ./build.sh All
