init:
  - git config --global core.autocrlf input
environment:
  matrix:
  # node.js
    - nodejs_version: "5"
os: Visual Studio 2015
before_build:
  - cmd: before_build.cmd
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
